/* ============================================================
   BANK KAMUS KATA KUNCI
   ------------------------------------------------------------
   Dipakai modul 17, diperiksa tests/17-kamus.test.mjs.

   Bentuk satu entri:
     kata      frasa yang muncul di naskah soal
     topik     alat yang ditandainya
     n, id     modul yang membahasnya (kosong = belum ada modulnya)
     tertukar  topik lain yang bunyinya mirip — inilah nilai utama
               sebuah kamus: bukan mendaftar, tapi MEMBEDAKAN
     jebakan   true kalau entri ini justru menandakan alat yang SALAH

   ATURAN
   1. Entri yang berasal dari `kamus` milik modul ajar disalin apa
      adanya. tests/17-kamus.test.mjs memastikan tidak ada yang beda.
   2. Pakai FPB, bukan gcd. Tidak boleh ada kata terlarang.
   3. Tiap klaim berangka harus benar — diperiksa tests/adu17.mjs.
   ============================================================ */

/* Judul tiap modul, dipakai modul 17 untuk mengelompokkan entrinya.
   Harus sama dengan `judul` di modul aslinya — diperiksa
   tests/17-kamus.test.mjs. */
export const JUDUL = {
  '01': 'Josephus Problem',
  '02': 'Digit Sum',
  '03': 'FPB & Euler’s Totient',
  '04': 'Frobenius / Chicken McNugget',
  '05': 'Rekursi Doubling',
  '06': 'Doubling pada Angka (MAI)',
  '07': 'Rekursi Bercabang (TIGA)',
  '08': 'Level & Topological Sort',
  '09': 'LCA · Leluhur Bersama Terdekat',
  '10': 'Lintasan Euler',
  '11': 'Kombinatorika',
  '12': 'Prefix Sum & Difference Array',
  '13': 'Dynamic Programming',
  '14': 'Pigeonhole & Skenario Terburuk',
  '15': 'Kotak Bersarang (Dilworth)',
};

export const ENTRI = [

  /* ============ DIPANEN DARI KAMUS TIAP MODUL AJAR ============ */
  { kata: '“melingkar” + “setiap ke-K dikeluarkan”',
    topik: 'Josephus', n: '01', id: 'josephus' },
  { kata: '“pangkat 2 terbesar ≤ n”',
    topik: 'Josephus K=2 / bye turnamen', n: '01', id: 'josephus' },
  { kata: 'x % 10 dan x / 10',
    topik: 'Digit sum / frekuensi digit', n: '02', id: 'digitsum' },
  { kata: '“sisa bagi 11”',
    topik: 'JEBAKAN — butuh jumlah berselang-seling, bukan digit sum', n: '02', id: 'digitsum',
    tertukar: 'Digit sum, yang dipakai untuk sisa bagi 9', jebakan: true },
  { kata: '“jumlahkan digitnya berulang sampai tersisa satu angka”',
    topik: 'Akar digit — ada rumus langsungnya, 1 + (n−1) mod 9', n: '02', id: 'digitsum',
    tertukar: 'Jumlah digit sekali jalan, yang belum tentu satu angka' },
  { kata: '“bilangan terkecil yang jumlah digitnya X”',
    topik: 'Isi angka 9 sebanyak mungkin dari belakang, sisanya ditaruh di depan',
    n: '02', id: 'digitsum',
    tertukar: 'Mengisi dari depan, yang justru menghasilkan bilangan lebih besar' },
  { kata: '“kelipatan Y terkecil yang jumlah digitnya X”',
    topik: 'Saring dulu: mustahil kalau X tidak habis dibagi FPB(Y, 9)',
    n: '02', id: 'digitsum',
    tertukar: 'Mencoba kelipatan satu per satu tanpa menyaring lebih dulu' },
  { kata: 'bobot (k − x + 1) × (y − k + 1)',
    topik: 'Mencacah berbobot — tiap angka dihitung sebanyak rentang yang memuatnya',
    n: '02', id: 'digitsum',
    tertukar: 'Mencacah biasa, yang menghitung tiap angka sekali saja' },
  { kata: 'F(B, A % B) — parameter tertukar',
    topik: 'FPB Euclidean', n: '03', id: 'gcd' },
  { kata: '“berapa yang koprima dengan n”',
    topik: 'Euler’s Totient φ(n)', n: '03', id: 'gcd' },
  { kata: '“ada berapa C yang FPB(A, C)-nya tepat B”',
    topik: 'Jalan pintas φ(A ÷ B) — nol kalau B tidak membagi habis A', n: '03', id: 'gcd',
    tertukar: 'Menghitung FPB satu per satu untuk seluruh C' },
  { kata: '“ubin terbesar yang menutupi lantai tanpa dipotong”',
    topik: 'FPB dari kedua ukuran lantainya', n: '03', id: 'gcd',
    tertukar: 'KPK, yang justru mencari yang terkecil bersama' },
  { kata: '“bersamaan lagi setelah berapa hari”, “berbunyi serentak”',
    topik: 'KPK, bukan FPB — hitung a × b ÷ FPB(a, b)', n: '03', id: 'gcd',
    tertukar: 'FPB, yang mencari pembagi bersama terbesar', jebakan: true },
  { kata: 'dua bilangan Fibonacci berurutan sebagai masukan',
    topik: 'Kasus terlama cara Euclid — banyaknya langkah paling banyak', n: '03', id: 'gcd',
    tertukar: 'Masukan biasa, yang cara Euclid-nya jauh lebih pendek' },
  { kata: 'dua ukuran wadah, “tidak bisa dibuat”',
    topik: 'Frobenius — CEK FPB DULU', n: '04', id: 'frobenius' },
  { kata: '“berapa terbesar yang tidak bisa dibentuk”',
    topik: 'Frobenius: ab − a − b (bila koprima)', n: '04', id: 'frobenius' },
  { kata: 'f(n) = f(n−1) + ubah(f(n−1))',
    topik: 'Rekursi doubling — panjang 2ⁿ, awalan tidak berubah', n: '05', id: 'doubling' },
  { kata: '“karakter ke-i dari string raksasa”',
    topik: 'Trik biner: hitung angka 1 pada biner i', n: '05', id: 'doubling' },
  { kata: 'f(f(x, y−1), y−1) — bersarang dua kali',
    topik: 'Doubling pada angka — efeknya jadi 2ʸ', n: '06', id: 'mai' },
  { kata: '“y = 666.666” atau angka raksasa lain',
    topik: 'Cari siklusnya, perkecil pakai sisa bagi', n: '06', id: 'mai' },
  { kata: 'rekursi bercabang f(N−1) + f(N−3)',
    topik: 'Hitung suku awal, cari polanya', n: '07', id: 'tiga' },
  { kata: 'kode bercabang menurut sisa bagi',
    topik: 'Kelompokkan menurut sisa baginya', n: '07', id: 'tiga' },
  { kata: '“prasyarat”, “harus selesai dulu”, panah antar kegiatan',
    topik: 'Kupas berlapis (level)', n: '08', id: 'toposort' },
  { kata: '“urutan ke berapa paling awal”',
    topik: 'Hitung leluhur + 1 — BUKAN level', n: '08', id: 'toposort',
    tertukar: 'Level, yaitu hasil kupas berlapis', jebakan: true },
  { kata: 'ada durasi tiap kegiatan',
    topik: 'Jalur kritis: durasi + prasyarat terlama', n: '08', id: 'toposort' },
  { kata: '“satu titik awal yang sama” untuk dua tujuan',
    topik: 'LCA', n: '09', id: 'lca' },
  { kata: '“hanya dapat dicapai dari satu tempat di atasnya”',
    topik: 'Pohon berakar — tiap titik satu induk', n: '09', id: 'lca' },
  { kata: '“total yang dikunjungi seminimal mungkin”',
    topik: 'LCA, bukan jarak terpendek biasa', n: '09', id: 'lca' },
  { kata: '“hanya boleh dilewati sekali” + “berapa hari/rute”',
    topik: 'Lintasan Euler', n: '10', id: 'euler' },
  { kata: '“setidaknya sekali” + “waktu minimum”',
    topik: 'Bukan Euler — jalan boleh diulang, jadi hitung ruas + ruas yang terpaksa diulang',
    n: '10', id: 'euler', tertukar: 'Lintasan Euler, yang tiap jalan maksimal sekali', jebakan: true },
  { kata: '“tanpa mengangkat pensil”',
    topik: 'Lintasan Euler, dengan kata lain', n: '10', id: 'euler' },
  { kata: '“lalu”, “kemudian”, tahapan berurutan',
    topik: 'Aturan perkalian', n: '11', id: 'kombi' },
  { kata: '“atau”, pilihan yang saling lepas',
    topik: 'Aturan penjumlahan — cek irisannya', n: '11', id: 'kombi' },
  { kata: '“setidaknya satu”, “minimal satu”',
    topik: 'Trik komplemen', n: '11', id: 'kombi' },
  { kata: '“boleh tidak memilih”',
    topik: 'Trik +1 lalu −1', n: '11', id: 'kombi' },
  { kata: '“urutan tidak diperhatikan”',
    topik: 'Kombinasi, bukan permutasi', n: '11', id: 'kombi' },
  { kata: '“duduk melingkar”',
    topik: 'Permutasi melingkar (n−1)!', n: '11', id: 'kombi' },
  { kata: '“jumlah dari X sampai Y”, ditanya berkali-kali',
    topik: 'Prefix sum', n: '12', id: 'prefix' },
  { kata: '“tambahkan sekian ke rentang L sampai R”',
    topik: 'Difference array', n: '12', id: 'prefix' },
  { kata: '“ada berapa yang … di antara posisi …”',
    topik: 'Prefix sum atas penanda 0/1', n: '12', id: 'prefix' },
  { kata: '“jumlah isi kotak dari baris a kolom b sampai …”',
    topik: 'Prefix sum dua dimensi', n: '12', id: 'prefix' },
  { kata: '“setelah memilih X, selama sekian hari tidak boleh X”',
    topik: 'DP dengan masa jeda', n: '13', id: 'dp' },
  { kata: '“total maksimum/minimum” + keputusan berurutan',
    topik: 'DP', n: '13', id: 'dp' },
  { kata: '“tepat satu dari beberapa pilihan tiap hari”',
    topik: 'Tabel DP satu baris per pilihan', n: '13', id: 'dp' },
  { kata: 'keputusan hari ini tidak memengaruhi besok',
    topik: 'Bukan DP — coba serakah dulu', n: '13', id: 'dp',
    tertukar: 'Dynamic Programming, yang keputusannya saling mengikat', jebakan: true },
  { kata: '"minimal supaya DIJAMIN" atau "PASTI"',
    topik: 'Skenario terburuk', n: '14', id: 'pigeon' },
  { kata: '"minimal supaya MUNGKIN" atau "bisa"',
    topik: 'Bukan skenario terburuk — jawabannya banyak wadah × syarat', n: '14', id: 'pigeon',
    tertukar: 'Skenario terburuk, yang bunyinya "supaya DIJAMIN"', jebakan: true },
  { kata: '"pernyataan mana yang PASTI benar"',
    topik: 'Cari satu contoh pembatal untuk tiap pernyataan', n: '14', id: 'pigeon' },
  { kata: '"berapa kemungkinan" tanpa kata dijamin',
    topik: 'Kombinatorika — mencacah kemungkinan, bukan mencari yang terjamin',
    n: '14', id: 'pigeon', tertukar: 'Skenario terburuk', jebakan: true },
  { kata: '"boleh dimasukkan kalau lebih kecil" + "maksimal satu di dalam"',
    topik: 'Kotak bersarang', n: '15', id: 'kotak' },
  { kata: '"paling sedikit yang terlihat dari luar"',
    topik: 'Banyaknya rantai paling sedikit', n: '15', id: 'kotak' },
  { kata: 'kotak berbentuk KUBUS',
    topik: 'Cukup cacah ukuran yang paling sering muncul', n: '15', id: 'kotak' },
  { kata: 'kotak berbentuk BALOK',
    topik: 'Rumus kembar gugur — butuh Dilworth penuh', n: '15', id: 'kotak',
    tertukar: 'Kotak kubus, yang cukup dicacah kembarnya', jebakan: true },

  /* ============ TAMBAHAN: PEMBEDA ANTAR TOPIK ============
     Entri di bawah tidak berasal dari modul mana pun. Semuanya
     dibuat untuk memisahkan topik yang bunyinya nyaris sama. */
  { kata: '“setiap PERSIMPANGAN dilewati tepat sekali”',
    topik: 'Hamilton — bukan Euler, dan jauh lebih sulit', n: '10', id: 'euler',
    tertukar: 'Lintasan Euler — yang mengurusi garis, bukan titik', jebakan: true },
  { kata: '“jalannya satu arah” (garis berujung panah)',
    topik: 'Rumus ganjil ÷ 2 gugur — pakai selisih panah keluar dan masuk',
    n: '10', id: 'euler', tertukar: 'Lintasan Euler dua arah', jebakan: true },
  { kata: '“petanya terpisah, tidak ada jalan penghubung”',
    topik: 'Rumus polos gugur — hitung tiap bagian sendiri, lalu jumlahkan', n: '10', id: 'euler',
    tertukar: 'Rumus Euler yang menganggap petanya nyambung', jebakan: true },
  { kata: '“satu titik punya dua panah masuk atau lebih”',
    topik: 'Bukan pohon — leluhur terdekatnya bisa lebih dari satu', n: '09', id: 'lca',
    tertukar: 'LCA pada pohon berakar', jebakan: true },
  { kata: '“level”-nya berapa, versus “urutan ke berapa”',
    topik: 'Dua angka BERBEDA. Level = kupas berlapis, urutan = hitung leluhur + 1',
    n: '08', id: 'toposort', tertukar: 'Level dan urutan sering dianggap sama', jebakan: true },
  { kata: '“lingkaran pertemanan”, “kelompok yang saling terhubung”',
    topik: 'Kelompokkan dulu, baru kalikan ukurannya', n: '11', id: 'kombi',
    tertukar: 'Terlihat seperti soal graf, padahal hitungannya kombinatorika' },
  { kata: '“dipilih untuk jabatan berbeda”',
    topik: 'Permutasi — urutan berpengaruh', n: '11', id: 'kombi',
    tertukar: 'Kombinasi, yang urutannya tidak berpengaruh' },
  { kata: '“A dan B tidak boleh dipilih bersamaan”',
    topik: 'Ada syarat antar-kelompok — perkalian polos kelebihan menghitung',
    n: '11', id: 'kombi', tertukar: 'Trik +1 lalu −1 yang polos', jebakan: true },
  { kata: '“berapa nilai TERBESAR dari indeks X sampai Y”',
    topik: 'Prefix sum gugur — nilai terbesar tidak bisa dikurangkan',
    n: '12', id: 'prefix', tertukar: 'Jumlah rentang, yang bisa dikurangkan', jebakan: true },
  { kata: '“berapa angka BERBEDA dalam rentang”',
    topik: 'Prefix sum gugur — yang unik tidak bisa dikurangkan', n: '12', id: 'prefix',
    tertukar: 'Mencacah lewat penanda 0/1', jebakan: true },
  { kata: '“lalu ubah nilai posisi ke-5”, lalu ditanya lagi',
    topik: 'Tabel bantunya basi — bangun ulang', n: '12', id: 'prefix',
    tertukar: 'Prefix sum biasa yang lariknya tidak berubah', jebakan: true },
  { kata: '“tiap hari ambil yang poinnya paling besar”',
    topik: 'Cara serakah — sering meleset. Di soal 2026 nomor 15 ia menjawab 28, padahal 32',
    n: '13', id: 'dp', tertukar: 'DP yang mempertimbangkan semua keadaan', jebakan: true },
  { kata: '“masa jedanya berbeda-beda tiap jenis”',
    topik: 'Trik dua terbesar gugur — pakai DP penuh', n: '13', id: 'dp',
    tertukar: 'DP jeda 1 yang cukup mengingat "kemarin ngapain"', jebakan: true },
  { kata: '“ada wadah yang isinya kurang dari syarat”',
    topik: 'MUSTAHIL — bukan angka', n: '14', id: 'pigeon',
    tertukar: 'Skenario terburuk biasa yang jawabannya berupa angka', jebakan: true },
  { kata: '“tiap pengambil boleh mengambil lebih dari satu”',
    topik: 'Rumus total − terkecil gugur', n: '14', id: 'pigeon',
    tertukar: 'Skenario terburuk satu-per-satu', jebakan: true },
  { kata: '“lebih kecil ATAU SAMA boleh dimasukkan”',
    topik: 'Tidak ada lagi kotak yang saling menolak — jawabannya selalu 1',
    n: '15', id: 'kotak', tertukar: 'Syarat "lebih kecil" yang tegas', jebakan: true },
  { kata: '“ada berapa cara berbeda menyusunnya”',
    topik: 'Mencacah susunan, bukan menghitung tumpukan', n: '11', id: 'kombi',
    tertukar: 'Kotak bersarang yang menghitung banyaknya tumpukan', jebakan: true },
  { kata: '“diulang 333.333 kali”, “setelah 17 putaran”',
    topik: 'Cari siklusnya, lalu perkecil pakai sisa bagi', n: '06', id: 'mai',
    tertukar: 'Menelusuri satu per satu sampai putaran terakhir' },
  { kata: '“kompleksitas waktu”, “berapa detik untuk N = …”',
    topik: 'Analisis Big-O — belum ada modulnya di lab ini' },
  { kata: '“paling kecil secara leksikografis”',
    topik: 'Ambil huruf terkecil yang masih memungkinkan, periksa dari kiri — belum ada modulnya' },
];

export default ENTRI;
